Azure/iot-edge

bindings/java/CMakeLists.txt, doc/java_how_to.md
Currently the JDK arch is hard-coded to 'amd64' which limits compatibility. This patch adds an option to specify JDK_ARCH using an environment variable and if not set it defaults to 'amd64'.
=> Add option to specify JDK_ARCH

modules/simulated_device/src/simulated_device.c, samples/simulated_device_cloud_upload/src/simulated_device_cloud_upload_lin.json, samples/simulated_device_cloud_upload/src/simulated_device_cloud_upload_win.json
The simulate sample always send a message every 10 seconds in currect time.
It is different with the BLE sample, which will make the "simlate" sample not simulate the BLE sample's behavior.
@darobs I change the pull request to develop branch. Besides this, I resolve your comments in [PullRequest 61](https://github.com/Azure/azure-iot-gateway-sdk/pull/61), you can view the incremental changes in the [second commit](https://github.com/Azure/azure-iot-gateway-sdk/commit/7b539056e99ce14325424c1b0c345723bb832058)
=> User can specific simulate sample's message sending period

bindings/nodejs/devdoc/nodejs_binding_requirements.md, bindings/nodejs/src/nodejs.cpp, bindings/nodejs/tests/nodejs_int/nodejs_int.cpp
Test confirms that NODEJS_Create is synchronous, which is implicitly required by the current design of the IoT Field Gateway
=> Add test for NODEJS_Create

tools/build.cmd
This is needed when running the build inside a Windows Docker container. CMake seems unable to locate the compiler otherwise.
=> Specify cmake generator explicitly in 32-bit Windows builds

tools/build.sh
The `--clean' option in `tools/build.sh` wasn't doing anything, as @GrantEdwards pointed out in issue #120.
=> Remove unused build script option

core/src/gateway_internal.c, core/tests/gateway_createfromjson_ut/gateway_createfromjson_ut.cpp, core/tests/gateway_ut/gateway_ut.cpp
In the course of investigating #86 I updated the submodule reference to azure-c-shared-utility locally and noticed new error spew in the console when running our gateway samples:
```
Error: Time:Tue Jan 31 18:10:21 2017 File:D:\tmp\azure-iot-gateway-sdk\deps\c-utility\src\vector.c Func:_VECTOR_size Line:328 invalid argument handle(NULL).
Error: Time:Tue Jan 31 18:10:21 2017 File:D:\tmp\azure-iot-gateway-sdk\deps\c-utility\src\vector.c Func:_VECTOR_find_if Line:291 invalid argument - handle(00000000), pred(50FB8280)
Error: Time:Tue Jan 31 18:10:21 2017 File:D:\tmp\azure-iot-gateway-sdk\deps\c-utility\src\vector.c Func:_VECTOR_size Line:328 invalid argument handle(NULL).
Error: Time:Tue Jan 31 18:10:21 2017 File:D:\tmp\azure-iot-gateway-sdk\deps\c-utility\src\vector.c Func:_VECTOR_find_if …
```
=> Only remove links if they weren't already removed

core/src/gateway_internal.c, core/tests/gateway_createfromjson_ut/gateway_createfromjson_ut.cpp, core/tests/gateway_ut/gateway_ut.cpp
This is a follow-up to #124. There were a few more VECTOR_size errors that we can avoid by testing for `gateway_handle->links == NULL`.
@nielsms
=> Avoid needless VECTOR_size errors

bindings/dotnetcore/dotnet-core-binding/Microsoft.Azure.IoT.Gateway.Tests/NetCoreInteropUnitTests.cs, tools/build.cmd
This fix gets .NET and .NET Core bindings building for Release.
=> Propagate config/platform to .NET binding build scripts

bindings/dotnetcore/dotnet-core-binding/Microsoft.Azure.IoT.Gateway/Broker.cs, bindings/dotnetcore/dotnet-core-binding/Microsoft.Azure.IoT.Gateway/BrokerInterop.cs, bindings/dotnetcore/dotnet-core-binding/Microsoft.Azure.IoT.Gateway/DotNetCoreModuleInstance.cs, bindings/dotnetcore/dotnet-core-binding/Microsoft.Azure.IoT.Gateway/NetCoreInterop.cs, bindings/dotnetcore/dotnet-core-binding/Microsoft.Azure.IoT.Gateway/Properties/AssemblyInfo.cs, tools/build_dotnet_core.cmd
- Mark implementation details as `internal`
- In build_dotnet_core.cmd, exit with an error if tests fail
I confirmed that unit tests pass and the sample still works.
=> Clarify Microsoft.Azure.IoT.Gateway's public interface

samples/nodejs_simple_sample/nodejs_modules/iothub_writer.js
Stringify the message content coming into the iothub_writer, so that it's visible and readable on the device explorer.
=> Have iothub_writer.js stringify the message content for better display Issue #167

modules/azure_functions/src/azure_functions.c, modules/azure_functions/tests/azure_functions_ut/azure_functions_ut.c, modules/logger/src/logger.c, modules/logger/tests/logger_ut/logger_ut.cpp
When logger and Azure Functions receives a message with empty content, it reports content as empty, rather than considering that an error.
=> Example modules handle empty content better.

modules/ble/tests/ble_c2d_ut/ble_c2d_ut.cpp, tools/build_dotnet_core.sh
I'm updating our submodule references in preparation to support VS 2017. The parson update caused build failures in one test suite, so I updated that as well. During my investigations, I changed `\` to `/` in the .NET Core binding build script--that didn't end up fixing anything, but it's something I've been meaning to do anyway so I'll keep it.
=> Update submodules and fix resulting build breaks

tools/build.cmd
Had to fix some things in our dependencies, then do a submodule dance, and finally update the build script.
The build script uses your Visual Studio environment to determine what to build. If you're in a "Developer Command Prompt for VS2015", then you'll build for VS 2015. If you're in a "Developer Command Prompt for 2017", then you'll build for 2017. If it's an environment that doesn't define VisualStudioVersion (e.g. vanilla command prompt), then you'll get an error (at least for now).
=> Support Visual Studio 2017 builds

bindings/nodejs/inc/nodejs_idle.h, bindings/nodejs/src/modules_manager.cpp, bindings/nodejs/src/nodejs_idle.cpp, tools/build_nodejs.cmd, tools/build_nodejs.ps1, tools/build_nodejs.sh
This PR includes changes that remove the need for maintaining a fork of Node.js. It achieves this by utilizing *libuv*'s support for [async callbacks](http://docs.libuv.org/en/v1.x/async.html).
Now that we're building from the [official Node.js](https://github.com/nodejs/node.git) repo the build script for building the Node.js bits now supports specifying the version you want built. If you just run `tools/build_nodejs.cmd` or `tools/build_nodejs.sh` without passing any parameters then it will build the current LTS version of Node.js (which as of this PR is *v6.10.1*). If you want to build a different version then you'd do the following on Windows:
```
tools\build_nodejs.cmd --node-version v7.7.4
```
If you wanted to build a 64 bit version of v7.7.4 then you'd do this:
``` …
```
=> Re-implement Node.js binding using libuv async

core/tests/outprocess_loader_ut/outprocess_loader_ut.c, proxy/gateway/java/gateway-remote-module/src/main/java/com/microsoft/azure/gateway/remote/CommunicationControlStrategy.java, proxy/gateway/native/src/proxy_gateway.c, proxy/gateway/native/tests/proxy_gateway_ut/proxy_gateway_ut.c, proxy/outprocess/src/module_loaders/outprocess_loader.c
1. Don't URL-encode control/message channel identifiers. The valid character sets for identifiers varies by platform, and on no platform does the valid character set conform to the RFCs for URL encoding. We'll let the underlying platform technologies (used by nanomsg) validate the identifier.
2. Don't add a ".ipc" suffix to the channel identifiers. On Posix-based platforms the identifier is actually a file path. If we change the file path in any way then it won't be where the user might expect it.
=> Improve channel identifiers

CMakeLists.txt, bindings/dotnetcore/dotnet-core-binding/E2ETestModule/E2ETestModule.csproj, bindings/dotnetcore/dotnet-core-binding/Microsoft.Azure.Devices.Gateway.Tests/Microsoft.Azure.Devices.Gateway.Tests.csproj, bindings/dotnetcore/dotnet-core-binding/Microsoft.Azure.Devices.Gateway/Microsoft.Azure.Devices.Gateway.csproj, samples/dotnet_core_module_sample/modules/PrinterModule/PrinterModule.csproj, samples/dotnet_core_module_sample/modules/SensorModule/SensorModule.csproj, tools/docs/c/Doxyfile, tools/docs/dotnetcore/Doxyfile, tools/release/bump_version/versions.json
Code changes are limited to the core (which includes loaders, the native part of bindings, etc) and the .NET Core assembly (changed the target from netstandard16 to netstandard13).
=> Bump versions for 2017-04-27 release

samples/hello_world/README.md
The headers need a space between the ### and the titles.
=> Fixed the headers for Github markdown in the readme.md

tools/build_nodejs.ps1
The quotes for setting NODE_INCLUDE and NODE_LIB were in the wrong place resulting in build failures where uv.h was not found.
Thanks @avranju for helping debug.
=> Fix position of quotes in powershell build script

bindings/java/gateway-java-binding/pom.xml, proxy/gateway/java/gateway-remote-module/pom.xml, samples/java_sample/java_modules/Printer/pom.xml, samples/java_sample/java_modules/Sensor/pom.xml
This PR fixes Java binding build error on Windows caused by default java compiler encoding specified by maven.
For your information, there are build error message when I tried on Japanese Windows:
```
[INFO] --- maven-compiler-plugin:3.3:testCompile (default-testCompile) @ gateway-java-binding ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding MS932, i.e. build is platform dependent!
[INFO] Compiling 2 source files to path\to\gwsdk\bindings\java\gateway-java-binding\target\test-classes
[ERROR] /path/to/gwsdk/bindings/java/gateway-java-binding/src/test/java/tests/unit/com/microsoft/azure/gateway/messaging/MessageTest.java:[281,27] この文字は、エンコーディングMS932にマップできません
[ERROR] …
```
=> Fix Java binding build error on Windows

bindings/java/src/java_module_host.c
This PR fixes issue #275.
This commit moves `JNIEnv*` variable from `JAVA_MODULE_HANDLE_DATA` structure to local variable.
The variable is assigned by JVM in `AttachCurrentThread` in both of start and receive functions,
it causes race condition of the variable, then segmentation fault is occurred in `ExceptionOccurred` JNI function.
So, the `JNIEnv*` variable should be local instead of a part of `JAVA_MODULE_HANDLE_DATA`.
=> Fix JNIEnv* share between start thread and receive thread

CMakeLists.txt, doc/devbox_setup.md, proxy/gateway/nodejs/package.json, samples/nodejs_remote_sample/README.md, tools/build.cmd, tools/build.sh
...because users may not have Node.js installed (or it might be an older version that doesn't meet our requirements).
Also, document that the new Node.js out-of-process modules feature requires at least Node.js v6.0.
=> Turn off Node.js out-of-process modules by default

tools/build_libuv.sh
The CMakeLists.txt in core assumes that libuv is installed in ${edge-root}/build_libuv/dist/lib
but this is not always the case. Some 64bit linux distributions will install libraries to ${prefix}/lib64 instead of ${prefix}/lib.
Fix this by forcing libdir to ${prefix}/lib instead of relying on distro-specific behaviour.
=> Specify libdir when configuring libuv

tools/build.sh
The Linux build script fails silently if the number of cores and the virtual memory on the host machine cause the `CORES2` variable to evaluate to zero. This is because the unix `expr` command returns a non-zero error code if the result is zero, even though zero is a legitimate result. I fixed it by discarding the status code; we only care about the expression result.
=> Don't exit build script if #cores evaluates to zero

jenkins/osx_c.sh, tools/build.sh
Until now you had to use CMake commands directly (or call jenkins/osx_c.sh). Now you can use tools/build.sh. Note that you need to pass the right flags, e.g., macOS doesn't support our BLE module so you have to pass `--disable-ble-module`.
The only problem was the logic we use to calculate available memory per core. I simply bypassed that logic for macOS; we can assume for now that macOS devices have enough memory per core to build without getting bogged down.
=> Fix #276: Support macOS builds from build.sh

bindings/dotnet/dotnet-binding/PrinterModule/DotNetPrinterModule.cs
When using the printer module to debug solutions it doesn't make sence that only messages coming from "Sensor" is printed.
=> Remove filter from message printing

gatewayFunctions.cmake, modules/iothub/devdoc/iothub.md, modules/iothub/src/iothub.c, modules/iothub/tests/iothub_ut/iothub_ut.cpp, modules/simulated_device/devdoc/simulated_device_requirements.md, modules/simulated_device/src/simulated_device.c
A device may not ever send telemetry, or send telemetry rarely, but the user might still need to have that device receive messages from the cloud.  The iothub module doesn't know about devices until it is sent a message about the device, so I added the ability to send a registration message to the iothub module.
The message has no telemetry, and does not send a d2c message, but the IoTHub device is created, and can receive messages.
Registration message is recognized by these properties:
>| PropertyName   | Description                                                                  |
>|----------------|------------------------------------------------------------------------------|
>| deviceName     | The device ID registered with IoT Hub                                        |
>| …
=> Allow a device to receive messages before sending telemetry.

proxy/outprocess/devdoc/outprocess_hld.md, samples/native_module_host_sample/README.md
Temporary fixes for bad links. The outprocess devdoc location( either in core/devdoc or in proxy/outprocess/devdoc ) needs to be finalized by maintainers.
=> bad links temporary fix

CMakeLists.txt, core/CMakeLists.txt, tools/build_libuv.cmd, tools/build_libuv.sh
=> Lock LibUV to commit w/ VS2017 support

Contributing.md
Point it to the iot-sdk-c contributing doc instead of the broken link to iot-sdk contributing doc.
=> Fix the broken link to azure-iot-sdk contributing doc

modules/iothub/devdoc/iothub.md, modules/iothub/inc/iothub.h, modules/iothub/src/iothub.c, modules/iothub/tests/iothub_ut/iothub_ut.cpp, samples/ble_gateway/src/gateway_sample.json, samples/simulated_device_cloud_upload/src/simulated_device_cloud_upload_intel_edison.json, samples/simulated_device_cloud_upload/src/simulated_device_cloud_upload_lin.json, samples/simulated_device_cloud_upload/src/simulated_device_cloud_upload_win.json
* Added RetryPolicy configuration json field
* devdoc updates
* Updated old ones and added some new unit tests
* Updated configuration json files of all samples using IotHub module
Issue refence: #378
=> Configrable RetryPolicy for IotHub -module

.gitignore
Some directories that used to be ignored are now listed in `git status` because we moved everything under the `/v1` folder. This tweak to the `.gitignore` file fixes that.
=> Ignore certain directories that have moved to /v1

modules/common/messageproperties.h, modules/iothub/devdoc/iothub.md, modules/iothub/src/iothub.c, modules/iothub/tests/iothub_ut/iothub_ut.cpp
Here is what I was talking about in #391 ('Message Delivered'-notification from IotHub). This feature is mandatory for us, so I just implemented it. If you are interested in having this kind of feature, here it is. If this is not useful to you, feel free to say no.
=> Iothub delivery notification

v1/gatewayFunctions.cmake
We frequently ask people to send us log files from rather obscure locations when one of our submodules fails to build. This change adds some useful information to the error message, directing the user to the right log files. It might help people figure out what's wrong without having to open a GitHub issue.
=> Print out a helpful message when a submodule fails to build

v1/README.md, v1/ThirdPartyNotices.txt, v1/bindings/dotnet/devdoc/dotnet_binding_hld.md, v1/bindings/dotnet/dotnet-binding/PrinterModule/DotNetPrinterModule.cs, v1/bindings/dotnetcore/devdoc/dotnet_core_binding_hld.md, v1/bindings/java/devdoc/java_binding_hld.md, v1/bindings/nodejs/devdoc/nodejs_binding_hld.md, v1/core/devdoc/dynamic_library_requirements.md, v1/core/devdoc/message_broker_requirements.md, v1/core/devdoc/module_loaders.md, v1/core/devdoc/module_loading_hld.md, v1/doc/commercial_gateway_kit/iot-hub-gateway-kit-c-iot-gateway-connect-device-to-cloud.md, v1/doc/commercial_gateway_kit/iot-hub-gateway-kit-c-lesson1-set-up-nuc.md, v1/doc/commercial_gateway_kit/iot-hub-gateway-kit-c-use-iot-gateway-for-data-conversion.md, v1/doc/connect_to_preconfigured_solutions/iot-suite-v1-gateway-kit-get-started-sensortag.md, v1/doc/connect_to_preconfigured_solutions/iot-suite-v1-gateway-kit-get-started-simulator.md, v1/doc/migration_from_v1_to_v2.md, v1/doc/module_development/iot-hub-iot-edge-create-module-java.md, v1/proxy/outprocess/devdoc/out-process-control-messages.md, v1/proxy/outprocess/devdoc/outprocess_hld.md, v1/samples/ble_gateway/iot-hub-iot-edge-physical-device.md, v1/samples/dotnet_core_module_sample/modules/PrinterModule/DotNetPrinterModule.cs, v1/samples/hello_world/iot-hub-linux-iot-edge-get-started.md, v1/samples/hello_world/iot-hub-windows-iot-edge-get-started.md, v1/samples/simulated_device_cloud_upload/iot-hub-linux-iot-edge-simulated-device.md, v1/samples/simulated_device_cloud_upload/iot-hub-windows-iot-edge-simulated-device.md
Non-ascii characters tend to be a problem for native compilers when the active codepage doesn't support them. We've encountered this several times, especially with snippets from Word documents that make their way into code comments (sometimes Word -> markdown -> code comments). This change replaces most of the characters I found by doing regex file search for "[^\x00-\x7F]" in VS code. It doesn't remove the byte order marks from the beginning of unicode files, and I left a few legalese characters (like the "registered" and "copyright" symbol) which I didn't want to deal with.
=> Replace non-ascii characters

v1/core/src/broker.c, v1/core/tests/broker_ut/broker_ut.cpp, v1/core/tests/outprocess_module_ut/outprocess_module_ut.c, v1/proxy/gateway/java/nanomsg-binding/java_nanomsg.c, v1/proxy/gateway/java/nanomsg-binding/tests/java_nanomsg_ut.c, v1/proxy/gateway/native/src/proxy_gateway.c, v1/proxy/gateway/native/tests/proxy_gateway_ut/proxy_gateway_ut.c, v1/proxy/outprocess/src/module_loaders/outprocess_module.c
If calls to our underlying message broker (nanomsg) are interrupted due to a posix signal (on *nix platforms), we interpret that as an error condition and fail. But it's not an error condition, and can actually be quite common (in fact it's more or less guaranteed if a custom module makes use of posix signals, e.g., for events).
This change adds handling logic after calls to nn_send(), nn_recv(), nn_close(), and nn_shutdown() to detect the interrupted condition (nn function returns -1, errno = EINTR) and retry the command as recommended by the nanomsg documentation.
Note that I didn't bother detecting EINTR when NN_DONTWAIT is specified, because in that case the function will return errno = EAGAIN, which we're already handling.
Note also there are some other nanomsg functions that can …
=> (#474) Retry when nn_send/recv/close/shutdown is interrupted by a signal

v1/CMakeLists.txt, v1/bindings/dotnetcore/CMakeLists.txt, v1/bindings/dotnetcore/src/adapters/dotnetcore_utils_linux.cpp, v1/bindings/dotnetcore/tests/CMakeLists.txt, v1/bindings/dotnetcore/tests/dotnetcore_e2e/CMakeLists.txt, v1/core/CMakeLists.txt, v1/core/inc/module_loaders/dotnet_core_loader.h, v1/jenkins/osx_c.sh, v1/samples/dotnet_core_module_sample/CMakeLists.txt, v1/samples/dotnet_core_module_sample/README.md, v1/samples/dotnet_core_module_sample/src/dotnet_core_module_sample_lin.json
With these changes, I can run `./dotnet_core_module_sample` on macOS (I haven't yet tried dotnet_core_managed_gateway).
=> Support .NET Core modules on macOS

v1/bindings/nodejs/CMakeLists.txt, v1/bindings/nodejs/tests/CMakeLists.txt
Running `v1/tools/build --enable-nodejs-binding --run-unittests` produced errors like this:
```
CMake Error at bindings/nodejs/tests/nodejs_int/CMakeLists.txt:29 (target_include_directories):
Cannot specify include directories for target "nodejs_int_exe" which is not
built by this project.
```
The problem was that `--run-unittests` was causing the `nodejs_int` test suite to be built even it has dependencies on `--run-e2e-tests`. `nodejs_int` are integration tests, and therefore should be tied to the `--run-e2e-tests` flag. This commit does that.
=> Wire Node.js binding tests into -Drun_e2e_tests=ON
