Azure/iot-edge

- bindings/dotnet/devdoc/dotnet_bindings_hld.md
- bindings/dotnet/devdoc/dotnet_bindings_requirements.md
- bindings/dotnet/devdoc/dotnet_bindings_requirements_hl.md
- bindings/dotnet/inc/dotnet.h
- bindings/dotnet/inc/dotnet_hl.h
Adding .NET Binding requirement and headers for Module.
> DotNet Binding 

- .gitignore
- bindings/uwp/uwp-binding/Microsoft.Azure.IoT.Gateway/Microsoft.Azure.IoT.Gateway.vcxproj
- bindings/uwp/uwp-binding/Microsoft.Azure.IoT.Gateway/Microsoft.Azure.IoT.Gateway.vcxproj.filters
- core/CMakeLists.txt
- core/devdoc/event_system_requirements.md
- core/devdoc/gateway_ll_requirements.md
- core/inc/gateway_ll.h
- core/inc/internal/event_system.h
- core/src/gateway_ll.c
- core/src/internal/event_system.c
- core/tests/CMakeLists.txt
- core/tests/event_system_unittests/CMakeLists.txt
- core/tests/event_system_unittests/event_system_unittests.cpp
- core/tests/event_system_unittests/main.c
- core/tests/gateway_ll_unittests/gateway_ll_unittests.cpp
- core/tests/gateway_ll_uwp_unittests/gateway_ll_uwp_unittests.cpp
- samples/CMakeLists.txt
- samples/callbacks_sample/CMakeLists.txt
- samples/callbacks_sample/src/main.c
This module allows for listening to interesting Gateway events and thus allowing development of Gateway plugins.
> Added an implementation of Event System

- README.md
Add a GZip Compression NodeJS module to the list of community modules.
> Include GZip Compression NodeJS module in list

- CMakeLists.txt
- core/CMakeLists.txt
- core/devdoc/outprocess_loader_requirements.md
- core/devdoc/outprocess_module_requirements.md
- core/src/module_loader.c
- core/tests/outprocess_loader_ut/outprocess_loader_ut.c
- proxy/modules/CMakeLists.txt
- proxy/modules/native_module_host/CMakeLists.txt
- proxy/modules/native_module_host/devdoc/native_module_host.md
- proxy/modules/native_module_host/inc/native_module_host.h
- proxy/modules/native_module_host/src/native_module_host.c
- proxy/modules/native_module_host/tests/CMakeLists.txt
- proxy/modules/native_module_host/tests/native_module_host_ut/CMakeLists.txt
- proxy/modules/native_module_host/tests/native_module_host_ut/main.c
- proxy/modules/native_module_host/tests/native_module_host_ut/native_module_host_ut.c
- proxy/outprocess/inc/module_loaders/outprocess_loader.h
- proxy/outprocess/inc/module_loaders/outprocess_module.h
- proxy/outprocess/src/module_loaders/outprocess_loader.c
- proxy/outprocess/src/module_loaders/outprocess_module.c
- samples/CMakeLists.txt
- samples/native_module_host_sample/CMakeLists.txt
- samples/native_module_host_sample/README.md
- samples/native_module_host_sample/src/main.c
- samples/native_module_host_sample/src/native_host_sample_lin.json
- samples/native_module_host_sample/src/native_host_sample_win.json
- samples/native_module_host_sample/src/remote_main.c
> Oop modules c module host requirements & code.

- CMakeLists.txt
- bindings/java/CMakeLists.txt
- bindings/java/src/java_module_host.c
- bindings/java/tests/host_ut/host_ut.c
- core/CMakeLists.txt
- core/src/control_message.c
- core/tests/dynamic_library_ut/CMakeLists.txt
- core/tests/dynamic_loader_ut/dynamic_loader_ut.c
- core/tests/gateway_createfromjson_ut/gateway_createfromjson_ut.cpp
- core/tests/gateway_e2e/CMakeLists.txt
- core/tests/gateway_ut/gateway_ut.cpp
- core/tests/gwmessage_ut/gwmessage_ut.c
- core/tests/java_loader_ut/java_loader_ut.c
- core/tests/module_loader_ut/module_loader_ut.c
- dependencies.cmake
- gatewayFunctions.cmake
- jenkins/osx_c.sh
- modules/azure_functions/src/azure_functions.c
- modules/hello_world/src/hello_world.c
- modules/identitymap/tests/idmap_ut/idmap_ut.cpp
- proxy/gateway/native/src/proxy_gateway.c
- proxy/gateway/native/tests/proxy_gateway_ut/proxy_gateway_ut.c
- proxy/message/src/control_message.c
- proxy/modules/native_module_host/CMakeLists.txt
- proxy/modules/native_module_host/src/native_module_host.c
- samples/java_sample/src/java_sample_mac.json
- samples/native_module_host_sample/src/native_host_sample_lin.json
These changes don't support the Node.js and .NET Core bindings yet, but I've been sitting on them awhile and I'd like to get them checked in. I'll do a separate PR when I add support for Node.js and .NET Core bindings.
> Build gateway SDK for macOS

- doc/devbox_setup.md
@chipalost @Andrew-buckley - tidying up the formatting in devbox-setup.md
> Tidy devbox setup doc

- jenkins/osx_c.sh
- proxy/gateway/java/CMakeLists.txt
- proxy/gateway/java/nanomsg-binding/java_nanomsg.c
@ancaantochi @Azure/iot-gateway-devs
> Add macOS support for Java remote modules

- bindings/java/src/java_module_host.c
- bindings/java/src/java_module_host_manager.c
- bindings/java/tests/host_ut/host_ut.c
- core/src/module_loaders/java_loader.c
@ancaantochi @Azure/iot-gateway-devs
> Silence annoying VECTOR errors when using Java modules

- samples/proxy_sample/README.md
> Fix broken link in proxy_sample README.md [#242]

- CMakeLists.txt
> Add check for CMake version with remote modules

- README.md
Rename OPC-UA Client to OPC Publisher and update repo URL + target version, add OPC Proxy, clean up formatting.
> Update OPC modules in README.md

- tools/Dockerfile
- Get a newer version of CMake from `jessie-backports`
- Install necessary dependencies (automake, libtool)
- Rename gateway SDK to IoT Edge
- Whitespace and other superfluous changes...not because they're more correct, but because I couldn't help myself.
> Update Dockerfile to build libuv

- README.md
Module has been moved to a new URL and have been upgraded for version of IoT Edge
> Update Proficy Historian module

- core/tests/gateway_e2e/dependencies.cmake
- jenkins/raspberrypi_c.sh
- modules/dependencies.cmake
Copy&paste C Devices SDK Jenkins script, a few updates, and I have workable cross-compile in Jenkins.
> Add the raspberry pi cros-compile to Jenkins build.

- modules/logger/devdoc/logger.md
logger module contains two typos. Fixed.
> Typos fixed

- CMakeLists.txt
- bindings/java/tests/real_string.c
- core/tests/dotnet_core_loader_ut/real_strings.h
- core/tests/dotnet_loader_ut/real_strings.h
- core/tests/dynamic_loader_ut/real_strings.h
- core/tests/java_loader_ut/real_strings.h
- core/tests/module_loader_ut/real_strings.c
- core/tests/node_loader_ut/real_strings.h
- core/tests/outprocess_loader_ut/real_strings.h
- core/tests/outprocess_module_ut/real_strings.h
Update the C-SDK and related submodules to latest release, handle the fallout from the more recent changes.  All tests passed in CI.
> Submodule update to C SDK 2017-08-11 release

- CMakeLists.txt
- core/tests/gateway_e2e/dependencies.cmake
- core/tests/testtools/iothub_test/dependencies.cmake
- modules/dependencies.cmake
- modules/iothub/CMakeLists.txt
- modules/logger/src/logger.c
- modules/logger/tests/logger_ut/logger_ut.cpp
use iothub_client shared library's new name.
fix strftime in logger
The C SDK moved parson, need to fix our build.
> Update to latest master in iothub sdk, pull in latest submodules to do so.

- v1/core/tests/testtools/iothub_test/src/iothub_account.c
- v1/core/tests/testtools/iothub_test/src/iothubtest.c
- v1/jenkins/osx_c.sh
- v1/jenkins/traceability.cmd
- v1/tools/toolchain/windriver/cmake/FindCURL.cmake
- v1/tools/toolchain/windriver/cmake/FindOpenSSL.cmake
- v1/tools/windriver_linux_c.sh
Snap to 11/17/2017 release of C SDK, apply the various fixes to get it to build and pass tests.
> Snap to sdk 11 17 2017 release

- README.md
Hi there! Microsoft Technology Center Moscow propose two modules for supporting ZWave protocol stack.
Probably we have to relocate to some other repository....
There are to modules - protocol gateway module and mapper for IoT Hub
https://github.com/MaxKhlupnov/SmartHive
> Added link to Zwave protocol modules

- README.md
- v1/samples/hello_world/iot-hub-linux-iot-edge-get-started.md
- v1/samples/hello_world/iot-hub-windows-iot-edge-get-started.md
- v1/samples/simulated_device_cloud_upload/iot-hub-linux-iot-edge-simulated-device.md
- v1/samples/simulated_device_cloud_upload/iot-hub-windows-iot-edge-simulated-device.md
There's a few places in the documentation that were affected by moving V1 into the "v1" directory.
> Some documentation needs to be updated because we moved v1 to "v1"

- index.html
Make the changes to gh-pages to reflect  source code move to V1
> Added V1 to the links which needed it.

- bindings/dotnetcore/dotnet-core-binding/Microsoft.Azure.Devices.Gateway/GatewayInterop.cs
- samples/dotnet_core_dynamic_add_module/Program.cs
- samples/dotnet_core_dynamic_add_module/README.md
- samples/dotnet_core_dynamic_add_module/dotnet_core_dynamic_add_module.csproj
- samples/dotnet_core_dynamic_add_module/links.json
- samples/dotnet_core_dynamic_add_module/module1_lin.json
- samples/dotnet_core_dynamic_add_module/module2_lin.json
- tools/build_dotnet_core.sh
Fixes issue #301
Note: Linux only support now. 
Todo: Windows support.
> Dynamic module addition ability for dotnet core gateway bindings (#301)

- v2/samples/azureiotedge-simulated-temperature-sensor/README.md
The deployed temperature sensor has fewer functionality then the source code provided by this sample. I modified the README to clarify which functions are available in the deployed version and which are new.
Please check @varunpuranik @darobs @damonbarry if this makes sense.
> V2 Samples - Clarifying functionality

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
Adding an issue template for GitHub Issues.
> Adding an issue template for GitHub Issues. 
